module.exports = {
    channels: {
        APP_INFO: 'app_info',
        LOAD_BUILDINGS: 'load_buildings',
        ADD_BUILDING: 'add_building',
        ADD_ROOM: 'add_room',
        LOAD_ROOMS: 'load_rooms',
        SEARCH_ROOMS: 'search_rooms',
        DELETE_ROOM: 'delete_room',
        EDIT_ROOM: 'edit_room',
        LOAD_SUBJECTS: 'load_subjects',
        EDIT_SUBJECT: 'edit_subject',
        DELETE_SUBJECT: 'delete_subject',
        ADD_SUBJECT: 'add_subject',
		
		//supuni's
        ADD_SCHEDULE: 'add_schedule',
        EDIT_SCHEDULE: 'edit_schedule',
        DELETE_SCHEDULE: 'delete_schedule',
        LOAD_SCHEDULE: 'load_schedule',
        SEARCH_SCHEDULE: 'search_schedule',
        LOAD_STUDENTS_FOR_TT: 'load_students_for_tt',

        //lecturers and sessions
        LOAD_SUBJECTS: 'load_subjects',
        EDIT_SUBJECT: 'edit_subject',
        DELETE_SUBJECT: 'delete_subject',
        ADD_SUBJECT: 'add_subject',
        SEARCH_SUBJECTS: 'search subjects',
        LOAD_LECTURERS: 'load_lecturers',
        ADD_LECTURER: 'add_lecturer',
        SEARCH_LECTURERS: 'search lecturers',
        DELETE_LECTURERS: 'delete lecturers',
        EDIT_LECTURERS: 'edit lecturers',
        ADD_SESSION: 'add_session',
        LOAD_SESSIONS: 'load_sessions',
        SEARCH_SESSIONS: 'search_sessions',
        DELETE_SESSION: 'delete_session',
        LOAD_TAGS: 'load_tags',

         // nimaya's
         ADD_YEARSEM: 'add_yearsem',
         LOAD_YEARSEMS: 'load_yearsem',
         ADD_PROGRAMME: 'add_programme',
         LOAD_PROGRAMMES: 'load_programmes',
         ADD_GROUP: 'add_group',
         LOAD_GROUPS: 'load_groups',
         ADD_STUDENT: 'add_student',
         
         SEARCH_STUDENTS: 'search_students',
         ADD_TAG: 'add_tag',
         LOAD_TAGS: 'load_tags',
         SEARCH_TAGS: 'search_tags',
         EDIT_TAG: 'load_tags',
         DELETE_TAG: 'search_tags',
         EDIT_STUDENT: 'load_tags',
         DELETE_STUDENT: 'search_tags',
         ADD_GROUPID: 'add_groupid',
         LOAD_GROUPID: 'load_groupid',
         ADD_SUBGROUPID: 'add_subgroupid',
         LOAD_SUBGROUPID: 'load_subgroupid',
         FIND_GROUPID: 'find_groupid',
         FIND_SUBGROUPID: 'find_subgroupid',
    },
};